repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.15.15
      hooks:
          # Run the linter.
          - id: ruff-check
            args: [--fix, "--extend-select=I,E", "--ignore=F401"]
          # Run the formatter
          - id: ruff-format

    - repo: https://github.com/biomejs/pre-commit
      rev: v2.4.16
      hooks:
          - id: biome-check
            files: ./src
            additional_dependencies: ["@biomejs/biome@2.4.16"]
    - repo: https://github.com/djlint/djLint
      rev: v1.36.4
      hooks:
          - id: djlint-reformat
            files: ^app/frontend/templates/
          - id: djlint
            files: ^app/frontend/templates/
