---
name: Frontend feature
about: Create a frontend feature request
title: ""
labels: "type: frontend"
assignees: ""
---

### Summary

<!-- Describe what should be done. -->

### Additional context

<!-- Add any other context, logs or screenshots about the feature request here, or 'N/A'. -->
