"""Added instructions

Revision ID: 82f5ff775bba
Revises: 2486b4bc2f0f
Create Date: 2026-06-04 09:36:27.357549

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82f5ff775bba"
down_revision: Union[str, Sequence[str], None] = "2486b4bc2f0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("instructions", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "instructions")
    # ### end Alembic commands ###
